CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (ticker_symbol VARCHAR(4), ticker_symbol_count INTEGER);


CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM COL0 AS ticker_symbol, COUNT(*) OVER MINUTE_SLIDING_WINDOW AS ticker_symbol_count
FROM "SOURCE_SQL_STREAM_001"
WINDOW MINUTE_SLIDING_WINDOW AS (
  PARTITION BY COL0
  RANGE INTERVAL '5' MINUTE PRECEDING);

