# This CF template generate an E-Mail whenever there is a EC2 instance create
# Bug - Need to edit CloudWatch Rule "EC2EventRule" from console to work

Transform: 'AWS::Serverless-2016-10-31'

# Parameters are CloudFormation features to pass input
# to your template when you create a stack
Parameters:
    BucketName:
        Type: String
    CodeKey:
        Type: String

Resources:
    EC2EventsTopic: 
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "EC2EventsTopic"

    EC2EventsTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: lherath@mitrai.com
        Protocol: email
        TopicArn: !Ref 'EC2EventsTopic'

    EC2EventRule: 
      Type: "AWS::Events::Rule"
      Properties: 
        Description: "EventRule"
        EventPattern: 
          source: 
            - "aws.ec2"
          detail: 
            eventName: 
              - "RunInstances"
        State: "ENABLED"
        Targets: 
          - 
            Arn: 
              Ref: "EC2EventsTopic"
            Id: "ID001"
            InputTransformer:
                InputPathsMap:
                  id: "$.id"
                  eventName: "$.detail.eventName"
                  awsRegion: "$.detail.awsRegion"
                  sourceIPAddress: "$.detail.sourceIPAddress"
                  time: "$.time"
                  userName: "$.detail.userIdentity.userName"
                  instanceId: "$.detail.responseElements.instancesSet.items[0].instanceId"
                  instanceType: "$.detail.responseElements.instancesSet.items[0].instanceType"
                InputTemplate: '"ID <id> eventName <eventName> awsRegion <awsRegion> sourceIPAddress <sourceIPAddress> time <time> userName <userName> instanceId <instanceId> instanceType <instanceType>."'
