# This CF template generate an E-Mail whenever there is a EC2 instance create
# Bug - Need to edit CloudWatch Rule "EC2EventRule" from console to work

Transform: 'AWS::Serverless-2016-10-31'

# Parameters are CloudFormation features to pass input
# to your template when you create a stack
# Parameters:
#     BucketName:
#         Type: String
#         Description : "Enter Bucket name of Lambda function zip."
#     CodeKey:
#         Type: String
#         Description : "Enter Folder name of Lambda function zip."

Resources:
    EC2CreateNotifyFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: index.handler
        Runtime: nodejs6.10
        CodeUri: s3://6282-lambda/ec2-create-notifier/ec2-create-notifier.zip

    EC2EventsTopic: 
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "EC2EventsTopic"

    EC2EventsTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: lherath@mitrai.com
        Protocol: email
        TopicArn: !Ref 'EC2EventsTopic'

    EC2EventRule: 
      Type: "AWS::Events::Rule"
      Properties: 
        Description: "EventRule"
        EventPattern: 
          source: 
            - "aws.ec2"
          detail: 
            eventName: 
              - "RunInstances"
        State: "ENABLED"
        Targets:
          - 
            Arn: 
              Fn::GetAtt:
                - EC2CreateNotifyFunction
                - Arn
            Id: "ID001"
          - 
            Arn:
              Ref: "EC2EventsTopic"
            Id: "ID002"



            # InputTransformer:
            #     InputPathsMap:
            #       id: "$.id"
            #       eventName: "$.detail.eventName"
            #       awsRegion: "$.detail.awsRegion"
            #       sourceIPAddress: "$.detail.sourceIPAddress"
            #       time: "$.time"
            #       userName: "$.detail.userIdentity.userName"
            #       instanceId: "$.detail.responseElements.instancesSet.items[0].instanceId"
            #       instanceType: "$.detail.responseElements.instancesSet.items[0].instanceType"
            #     InputTemplate: '"ID <id> eventName <eventName> awsRegion <awsRegion> sourceIPAddress <sourceIPAddress> time <time> userName <userName> instanceId <instanceId> instanceType <instanceType>."'
