php-demo:
  image: XXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/mytest-project-repo:v3
  cpu_shares: 100
  mem_limit: 134217728
  ports:
    - "80:80"
  entrypoint:
    - "/usr/sbin/apache2"
    - "-D"
    - "FOREGROUND"
